file(WRITE ${INSTALL_DIR}/bin/python${MAJOR}${MINOR}._pth "python${MAJOR}${MINOR}.zip\r\n.\r\nimport site")
file(WRITE ${INSTALL_DIR}/bin/Lib/site-packages/start_path.pth "import sys;import os;sys.path.insert(0,os.path.dirname(sys.argv[0]));")

set(pip ${INSTALL_DIR}/bin/get-pip.py)
if (NOT EXISTS ${pip})
    message("downloading get-pip.py")
    file(DOWNLOAD https://bootstrap.pypa.io/get-pip.py ${pip} SHOW_PROGRESS)
    message("installing pip")
    execute_process(COMMAND ${PYTHON_EXE} ${pip} --no-warn-script-location RESULT_VARIABLE err)
    if (NOT "${err}" STREQUAL "0" )
        message(FATAL_ERROR "cpython install pip error : ${err}")
    endif ()
endif ()