execute_process(COMMAND git -C ${SRC_DIR} clean -xfd)
execute_process(COMMAND git -C ${SRC_DIR} reset --hard)

set(file ${SRC_DIR}/Modules/Setup)
file(READ ${file} content)
string(REPLACE "#zlib  zlibmodule.c" "zlib  zlibmodule.c -I${ZLIB_INCLUDES} -L${ZLIB_LDFLAGS}" content "${content}")
string(REPLACE "# _ssl _ssl.c $(OPENSSL_INCLUDES) $(OPENSSL_LDFLAGS)" " _ssl _ssl.c -I${OPENSSL_INCLUDES} -L${OPENSSL_LDFLAGS}" content "${content}")
string(REPLACE "#     -l:libssl.a" "     -l:libssl.a" content "${content}")
string(REPLACE "#     -l:libcrypto.a" "     -l:libcrypto.a" content "${content}")
string(REPLACE "# _hashlib _hashopenssl.c $(OPENSSL_INCLUDES) $(OPENSSL_LDFLAGS)" " _hashlib _hashopenssl.c -I${OPENSSL_INCLUDES} -L${OPENSSL_LDFLAGS}" content "${content}")
file(WRITE ${file} "${content}")