#pragma once

#include <optional>
#include "srk/ByteArray.h"

#ifdef SRK_EXT_HID_EXPORTS
#	define SRK_EXT_HID_DLL SRK_DLL_EXPORT
#else
#	define SRK_EXT_HID_DLL SRK_DLL_IMPORT
#endif

#ifndef SRK_EXT_HID_ENUM
#	define SRK_EXT_HID_ENUM

#	define SRK_EXT_HID_ENUM_HIDReportItemType \
			SRK_EXT_HID_ENUM_ELEMENT(MAIN, 0) \
			SRK_EXT_HID_ENUM_ELEMENT(GLOBAL, 1) \
			SRK_EXT_HID_ENUM_ELEMENT(LOCAL, 2) \
			SRK_EXT_HID_ENUM_ELEMENT(RESERVED, 3) \

#	define SRK_EXT_HID_ENUM_HIDReportMainItemTag \
			SRK_EXT_HID_ENUM_ELEMENT(INPUT, 0x8) \
			SRK_EXT_HID_ENUM_ELEMENT(OUTPUT, 0x9) \
			SRK_EXT_HID_ENUM_ELEMENT(COLLECTION, 0xA) \
			SRK_EXT_HID_ENUM_ELEMENT(FEATURE, 0xB) \
			SRK_EXT_HID_ENUM_ELEMENT(END_COLLECTION, 0xC) \

#	define SRK_EXT_HID_ENUM_HIDReportGlobalItemTag \
			SRK_EXT_HID_ENUM_ELEMENT(USAGE_PAGE, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(LOGICAL_MINIMUM, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(LOGICAL_MAXIMUM, 0x2) \
			SRK_EXT_HID_ENUM_ELEMENT(PHYSICAL_MINIMUM, 0x3) \
			SRK_EXT_HID_ENUM_ELEMENT(PHYSICAL_MAXIMUM, 0x4) \
			SRK_EXT_HID_ENUM_ELEMENT(UNIT_EXPONENT, 0x5) \
			SRK_EXT_HID_ENUM_ELEMENT(UNIT, 0x6) \
			SRK_EXT_HID_ENUM_ELEMENT(REPORT_SIZE, 0x7) \
			SRK_EXT_HID_ENUM_ELEMENT(REPORT_ID, 0x8) \
			SRK_EXT_HID_ENUM_ELEMENT(REPORT_COUNT, 0x9) \
			SRK_EXT_HID_ENUM_ELEMENT(PUSH, 0xA) \
			SRK_EXT_HID_ENUM_ELEMENT(POP, 0xB) \

#	define SRK_EXT_HID_ENUM_HIDReportLocalItemTag \
			SRK_EXT_HID_ENUM_ELEMENT(USAGE, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(USAGE_MINIMUM, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(USAGE_MAXIMUM, 0x2) \
			SRK_EXT_HID_ENUM_ELEMENT(DESIGNATOR_INDEX, 0x3) \
			SRK_EXT_HID_ENUM_ELEMENT(DESIGNATOR_MINIMUM, 0x4) \
			SRK_EXT_HID_ENUM_ELEMENT(DESIGNATOR_MAXIMUM, 0x5) \
			SRK_EXT_HID_ENUM_ELEMENT(STRING_INDEX, 0x6) \
			SRK_EXT_HID_ENUM_ELEMENT(STRING_MINIMUM, 0x7) \
			SRK_EXT_HID_ENUM_ELEMENT(STRING_MAXIMUM, 0x8) \
			SRK_EXT_HID_ENUM_ELEMENT(DELIMITER, 0xA) \

#	define SRK_EXT_HID_ENUM_HIDReportUsagePageType \
			SRK_EXT_HID_ENUM_ELEMENT(UNDEFINED, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(GENERIC_DESKTOP, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(SIMULATION_CONTROLS, 0x2) \
			SRK_EXT_HID_ENUM_ELEMENT(VR_CONTROLS, 0x3) \
			SRK_EXT_HID_ENUM_ELEMENT(SPORT_CONTROLS, 0x4) \
			SRK_EXT_HID_ENUM_ELEMENT(GAME_CONTROLS, 0x5) \
			SRK_EXT_HID_ENUM_ELEMENT(GENERIC_DEVICE_CONTROLS, 0x6) \
			SRK_EXT_HID_ENUM_ELEMENT(KEYBOARD_OR_KEYPAD, 0x7) \
			SRK_EXT_HID_ENUM_ELEMENT(LEDS, 0x8) \
			SRK_EXT_HID_ENUM_ELEMENT(BUTTON, 0x9) \
			SRK_EXT_HID_ENUM_ELEMENT(ORDINALS, 0xA) \
			SRK_EXT_HID_ENUM_ELEMENT(TELEPHONY_DEVICES, 0xB) \
			SRK_EXT_HID_ENUM_ELEMENT(CONSUMER_DEVICES, 0xC) \
			SRK_EXT_HID_ENUM_ELEMENT(DIGITIZERS, 0xD) \
			SRK_EXT_HID_ENUM_ELEMENT(HAPTICS, 0xE) \
			SRK_EXT_HID_ENUM_ELEMENT(PID, 0xF) \
			SRK_EXT_HID_ENUM_ELEMENT(UNICODE, 0x10) \
			SRK_EXT_HID_ENUM_ELEMENT(EYE_AND_HEAD_TRACKERS, 0x12) \
			SRK_EXT_HID_ENUM_ELEMENT(AUXILIARY_DISPLAY, 0x14) \
			SRK_EXT_HID_ENUM_ELEMENT(SENSORS, 0x20) \
			SRK_EXT_HID_ENUM_ELEMENT(MEDIA_INSTRUMENT, 0x40) \
			SRK_EXT_HID_ENUM_ELEMENT(BRAILLE_DISPLAY, 0x41) \
			SRK_EXT_HID_ENUM_ELEMENT(LIGHTING_AND_ILLUMINATION, 0x59) \
			SRK_EXT_HID_ENUM_ELEMENT(MONITOR, 0x80) \
			SRK_EXT_HID_ENUM_ELEMENT(MONITOR_ENUMERATED_VALUES, 0x81) \
			SRK_EXT_HID_ENUM_ELEMENT(VESA_VIRTUAL_CONTROLS, 0x82) \
			SRK_EXT_HID_ENUM_ELEMENT(VESA_COMMAND, 0x83) \
			SRK_EXT_HID_ENUM_ELEMENT(POWER_DEVICE, 0x84) \
			SRK_EXT_HID_ENUM_ELEMENT(BATTERY_SYSTEM, 0x85) \
			SRK_EXT_HID_ENUM_ELEMENT(POWER_PAGES_BEGIN, 0x86) \
			SRK_EXT_HID_ENUM_ELEMENT(POWER_PAGES_END, 0x87) \
			SRK_EXT_HID_ENUM_ELEMENT(BAR_CODE_SCANNER, 0x8C) \
			SRK_EXT_HID_ENUM_ELEMENT(SCALE, 0x8D) \
			SRK_EXT_HID_ENUM_ELEMENT(MAGNETIC_STRIPE_REDING_DEVICES, 0x8E) \
			SRK_EXT_HID_ENUM_ELEMENT(RESERVED_POINT_OF_SALE, 0x8F) \
			SRK_EXT_HID_ENUM_ELEMENT(CAMERA_CONTROL, 0x90) \
			SRK_EXT_HID_ENUM_ELEMENT(ARCADE, 0x91) \
			SRK_EXT_HID_ENUM_ELEMENT(GAMING_DEVICE, 0x92) \
			SRK_EXT_HID_ENUM_ELEMENT(FIDO_ALLIANCE, 0xF1D0) \
			SRK_EXT_HID_ENUM_ELEMENT(VENDOR_DEFINED_BEGIN, 0xFF00) \
			SRK_EXT_HID_ENUM_ELEMENT(VENDOR_DEFINED_END, 0xFFFF) \

#	define SRK_EXT_HID_ENUM_HIDReportGenericDesktopPageType \
			SRK_EXT_HID_ENUM_ELEMENT(UNDEFINED, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(POINTER, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(MOUSE, 0x2) \
			SRK_EXT_HID_ENUM_ELEMENT(JOYSTICK, 0x4) \
			SRK_EXT_HID_ENUM_ELEMENT(GAMEPAD, 0x5) \
			SRK_EXT_HID_ENUM_ELEMENT(KEYBOARD, 0x6) \
			SRK_EXT_HID_ENUM_ELEMENT(KEYPAD, 0x7) \
			SRK_EXT_HID_ENUM_ELEMENT(MULTI_AXIS_CONTROLLER, 0x8) \
			SRK_EXT_HID_ENUM_ELEMENT(TABLET_PC_SYSTEM_CONTROLS, 0x9) \
			SRK_EXT_HID_ENUM_ELEMENT(WATER_COOLING_DEVICE, 0xA) \
			SRK_EXT_HID_ENUM_ELEMENT(COMPUTER_CHASSIS_DEVICE, 0xB) \
			SRK_EXT_HID_ENUM_ELEMENT(WIRELESS_RADIO_CONTROLS, 0xC) \
			SRK_EXT_HID_ENUM_ELEMENT(PORTABLE_DEVICE_CONTROLS, 0xD) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MULTI_AXIS_CONTROLLER, 0xE) \
			SRK_EXT_HID_ENUM_ELEMENT(SPATIAL_CONTROLLER, 0xF) \
			SRK_EXT_HID_ENUM_ELEMENT(ASSISTIVE_CONTROL, 0x10) \
			SRK_EXT_HID_ENUM_ELEMENT(DEVICE_DOCK, 0x11) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE, 0x12) \
			SRK_EXT_HID_ENUM_ELEMENT(X, 0x30) \
			SRK_EXT_HID_ENUM_ELEMENT(Y, 0x31) \
			SRK_EXT_HID_ENUM_ELEMENT(Z, 0x32) \
			SRK_EXT_HID_ENUM_ELEMENT(RX, 0x33) \
			SRK_EXT_HID_ENUM_ELEMENT(RY, 0x34) \
			SRK_EXT_HID_ENUM_ELEMENT(RZ, 0x35) \
			SRK_EXT_HID_ENUM_ELEMENT(SLIDER, 0x36) \
			SRK_EXT_HID_ENUM_ELEMENT(DIAL, 0x37) \
			SRK_EXT_HID_ENUM_ELEMENT(WHEEL, 0x38) \
			SRK_EXT_HID_ENUM_ELEMENT(HAT_SWITCH, 0x39) \
			SRK_EXT_HID_ENUM_ELEMENT(COUNTED_BUFFER, 0x3A) \
			SRK_EXT_HID_ENUM_ELEMENT(BYTE_COUNT, 0x3B) \
			SRK_EXT_HID_ENUM_ELEMENT(MOTION_WAKEUP, 0x3C) \
			SRK_EXT_HID_ENUM_ELEMENT(START, 0x3D) \
			SRK_EXT_HID_ENUM_ELEMENT(SELECT, 0x3E) \
			SRK_EXT_HID_ENUM_ELEMENT(VX, 0x40) \
			SRK_EXT_HID_ENUM_ELEMENT(VY, 0x41) \
			SRK_EXT_HID_ENUM_ELEMENT(VZ, 0x42) \
			SRK_EXT_HID_ENUM_ELEMENT(VBRX, 0x43) \
			SRK_EXT_HID_ENUM_ELEMENT(VBRY, 0x44) \
			SRK_EXT_HID_ENUM_ELEMENT(VBRZ, 0x45) \
			SRK_EXT_HID_ENUM_ELEMENT(VNO, 0x46) \
			SRK_EXT_HID_ENUM_ELEMENT(FEATURE_NOTIFICATION, 0x47) \
			SRK_EXT_HID_ENUM_ELEMENT(RESOLUTION_MULTIPLIER, 0x48) \
			SRK_EXT_HID_ENUM_ELEMENT(QX, 0x49) \
			SRK_EXT_HID_ENUM_ELEMENT(QY, 0x4A) \
			SRK_EXT_HID_ENUM_ELEMENT(QZ, 0x4B) \
			SRK_EXT_HID_ENUM_ELEMENT(QW, 0x4C) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_CONTROL, 0x80) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_POWER_DOWN, 0x81) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_SLEEP, 0x82) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_WAKEUP, 0x83) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_CONTEXT_MENU, 0x84) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MAIN_MENU, 0x85) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_APP_MENU, 0x86) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_HELP, 0x87) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_EXIT, 0x88) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_SELECT, 0x89) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_RIGHT, 0x8A) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_LEFT, 0x8B) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_UP, 0x8C) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_MENU_DOWN, 0x8D) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_COLD_RESTART, 0x8E) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_WARM_RESTART, 0x8F) \
			SRK_EXT_HID_ENUM_ELEMENT(DPAD_UP, 0x90) \
			SRK_EXT_HID_ENUM_ELEMENT(DPAD_DOWN, 0x91) \
			SRK_EXT_HID_ENUM_ELEMENT(DPAD_RIGHT, 0x92) \
			SRK_EXT_HID_ENUM_ELEMENT(DPAD_LEFT, 0x93) \
			SRK_EXT_HID_ENUM_ELEMENT(INDEX_TRIGGER, 0x94) \
			SRK_EXT_HID_ENUM_ELEMENT(PALM_TRIGGER, 0x95) \
			SRK_EXT_HID_ENUM_ELEMENT(THUMBSTICK, 0x96) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_FUNCTION_SHIFT, 0x97) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_FUNCTION_SHIFT_LOCK, 0x98) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_FUNCTION_SHIFT_LOCK_INDICATOR, 0x99) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISMISS_NOTIFICATION, 0x9A) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DO_NOT_DISTURB, 0x9B) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DOCK, 0xA0) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_UNDOCK, 0xA1) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_SETUP, 0xA2) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_BREAK, 0xA3) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DEBUGGER_BREAK, 0xA4) \
			SRK_EXT_HID_ENUM_ELEMENT(APPLICATION_BREAK, 0xA5) \
			SRK_EXT_HID_ENUM_ELEMENT(APPLICATION_DEBUGGER_BREAK, 0xA6) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_SPEATER_MUTE, 0xA7) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_HIBERNATE, 0xA8) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_INVERT, 0xB0) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_INTERNAL, 0xB1) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_EXTERNAL, 0xB2) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_BOTH, 0xB3) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_DUAL, 0xB4) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_TOGGLE_INT_OR_EXT_MODE, 0xB5) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_SWAP_PRIMARY_OR_SECONDARY, 0xB6) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_TOGGLE_LCD_AUTOSCALE, 0xB7) \
			SRK_EXT_HID_ENUM_ELEMENT(SENSOR_ZONE, 0xC0) \
			SRK_EXT_HID_ENUM_ELEMENT(RPM, 0xC1) \
			SRK_EXT_HID_ENUM_ELEMENT(COOLANT_LEVEL, 0xC2) \
			SRK_EXT_HID_ENUM_ELEMENT(COOLANT_CRITICAL_LEVEL, 0xC3) \
			SRK_EXT_HID_ENUM_ELEMENT(COOLANT_PUMP, 0xC4) \
			SRK_EXT_HID_ENUM_ELEMENT(CHASSIS_ENCLOSURE, 0xC5) \
			SRK_EXT_HID_ENUM_ELEMENT(WIRELESS_RADIO_BUTTON, 0xC6) \
			SRK_EXT_HID_ENUM_ELEMENT(WIRELESS_RADIO_LED, 0xC7) \
			SRK_EXT_HID_ENUM_ELEMENT(WIRELESS_RADIO_SLIDER_SWITCH, 0xC8) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_ROTATION_LOCK_BUTTON, 0xC9) \
			SRK_EXT_HID_ENUM_ELEMENT(SYSTEM_DISPLAY_ROTATION_LOCK_SLIDER_SWITCH, 0xCA) \
			SRK_EXT_HID_ENUM_ELEMENT(CONTROL_ENABLE, 0xCB) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_UNIQUE_ID, 0xD0) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_VENDOR_ID, 0xD1) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_PRIMARY_USAGE_PAGE, 0xD2) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_PRIMARY_USAGE_ID, 0xD3) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_DOCKING_STATE, 0xD4) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_DISPLAY_OCCLUSION, 0xD5) \
			SRK_EXT_HID_ENUM_ELEMENT(DOCKABLE_DEVICE_OBJECT_TYPE, 0xD6) \

#	define SRK_EXT_HID_ENUM_HIDReportConsumerPageType \
			SRK_EXT_HID_ENUM_ELEMENT(UNDEFINED, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(CONSUMER_CONTROL, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(NUMERIC_KEY_PAD, 0x2) \
			SRK_EXT_HID_ENUM_ELEMENT(PROGRAMMABLE_BUTTONS, 0x3) \
			SRK_EXT_HID_ENUM_ELEMENT(MICROPHONE, 0x4) \
			SRK_EXT_HID_ENUM_ELEMENT(HEADPHONE, 0x5) \
			SRK_EXT_HID_ENUM_ELEMENT(GRAPHIC_EQUALIZER, 0x6) \

#	define SRK_EXT_HID_ENUM_HIDReportButtonPageType \
			SRK_EXT_HID_ENUM_ELEMENT(NO_BUTTON_PRESED, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(BUTTON_1, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(BUTTON_65535, 0xFFFF) \

#	define SRK_EXT_HID_ENUM_HIDReportCollectionData \
			SRK_EXT_HID_ENUM_ELEMENT(PHYSICAL, 0x0) \
			SRK_EXT_HID_ENUM_ELEMENT(APPLICATION, 0x1) \
			SRK_EXT_HID_ENUM_ELEMENT(LOGICAL, 0x2) \
			SRK_EXT_HID_ENUM_ELEMENT(REPORT, 0x3) \
			SRK_EXT_HID_ENUM_ELEMENT(NAMED_ARRAY, 0x4) \
			SRK_EXT_HID_ENUM_ELEMENT(USAGE_MODIFIER, 0x5) \
			SRK_EXT_HID_ENUM_ELEMENT(USAGE_SWITCH, 0x6) \
			SRK_EXT_HID_ENUM_ELEMENT(RESERVED_BEGIN, 0x07) \
			SRK_EXT_HID_ENUM_ELEMENT(RESERVED_END, 0x7F) \
			SRK_EXT_HID_ENUM_ELEMENT(VENDOR_DEFINED_BEGIN, 0x80) \
			SRK_EXT_HID_ENUM_ELEMENT(VENDOR_DEFINED_END, 0xFF) \

#endif

namespace srk::extensions {
	class HIDDeviceInfo;
	class HIDDevice;


	enum class HIDReportItemType : uint8_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportItemType
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportMainItemTag : uint8_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportMainItemTag
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportGlobalItemTag : uint8_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportGlobalItemTag
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportLocalItemTag : uint8_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportLocalItemTag
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportUsagePageType : uint32_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportUsagePageType
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportGenericDesktopPageType : uint32_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportGenericDesktopPageType
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportConsumerPageType : uint32_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportConsumerPageType
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportButtonPageType : uint32_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportButtonPageType
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	enum class HIDReportCollectionData : uint16_t {
#define SRK_EXT_HID_ENUM_ELEMENT(a, b) a = b,
		SRK_EXT_HID_ENUM_HIDReportCollectionData
#undef SRK_EXT_HID_ENUM_ELEMENT
	};


	using HIDUsagePage = uint16_t;
	using HIDUsage = uint16_t;


	struct SRK_EXT_HID_DLL HIDReportDescriptorItem {
		HIDReportItemType type;
		uint8_t size;
		uint16_t tag;

		static size_t SRK_CALL read(const void* data, size_t length, HIDReportDescriptorItem& item);
		static bool SRK_CALL write(ByteArray& dst, const HIDReportDescriptorItem& item, const void* data);
		static void SRK_CALL write(ByteArray& dst, HIDReportItemType type, uint8_t tag, uint32_t data);
		static void SRK_CALL write(ByteArray& dst, HIDReportItemType type, uint8_t tag, int32_t data);
		static void SRK_CALL write(ByteArray& dst, HIDReportItemType type, uint8_t tag);
	};


	struct SRK_EXT_HID_DLL HIDReportDescriptor {
		static std::string SRK_CALL toString(const void* data, size_t length);
	};


	class SRK_EXT_HID_DLL HID {
	public:
		static constexpr size_t IN_TIMEOUT_BLOCKING = (std::numeric_limits<size_t>::max)();
		static constexpr size_t OUT_ERROR = (std::numeric_limits<size_t>::max)();
		static constexpr size_t OUT_WAITTING = OUT_ERROR - 1;

		using EnumDevicesCallback = bool(SRK_CALL*)(const HIDDeviceInfo& info, void* userData);

		static void SRK_CALL enumDevices(void* userData, EnumDevicesCallback);

		static bool SRK_CALL isValid(const HIDDeviceInfo& info);
		static bool SRK_CALL isValid(const HIDDevice& device);

		static uint16_t SRK_CALL getVendorID(const HIDDeviceInfo& info);
		static uint16_t SRK_CALL getProductID(const HIDDeviceInfo& info);
		static std::string_view SRK_CALL getManufacturerString(const HIDDeviceInfo& info);
		static std::string_view SRK_CALL getProductString(const HIDDeviceInfo& info);
		static std::string_view SRK_CALL getPath(const HIDDeviceInfo& info);
		static HIDUsagePage SRK_CALL getUsagePage(const HIDDeviceInfo& info);
		static HIDUsage SRK_CALL getUsage(const HIDDeviceInfo& info);
		static int32_t SRK_CALL getIndex(const HIDDeviceInfo& info);

		static HIDDevice* SRK_CALL open(const std::string_view& path);
		static void SRK_CALL close(HIDDevice& device);

		static ByteArray SRK_CALL getReportDescriptor(const HIDDevice& device);

		static size_t SRK_CALL read(HIDDevice& device, void* data, size_t dataLength, size_t timeout);
		static size_t SRK_CALL write(HIDDevice& device, const void* data, size_t dataLength, size_t timeout);

		inline static bool SRK_CALL isSuccess(size_t rst) {
			return rst < OUT_WAITTING;
		}
	};
}