#pragma once

#include "DeviceBase.h"
#include "srk/modules/inputs/GenericKeyboard.h"

namespace srk::modules::inputs::direct_input {
	class SRK_MODULE_DLL KeyboardDriver : public IGenericKeyboardDriver {
	public:
		virtual ~KeyboardDriver();

		static KeyboardDriver* SRK_CALL create(Input& input, srk_IDirectInputDevice* dev);

		virtual bool SRK_CALL readStateFromDevice(GenericKeyboard::Buffer& buffer) const override;

	private:
		KeyboardDriver(Input& input, srk_IDirectInputDevice* dev);

		IntrusivePtr<Input> _input;
		srk_IDirectInputDevice* _dev;

		inline static constexpr KeyboardVirtualKeyCode SK_VK[] = {
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::ESCAPE,
			KeyboardVirtualKeyCode::_1,
			KeyboardVirtualKeyCode::_2,
			KeyboardVirtualKeyCode::_3,
			KeyboardVirtualKeyCode::_4,
			KeyboardVirtualKeyCode::_5,
			KeyboardVirtualKeyCode::_6,
			KeyboardVirtualKeyCode::_7,
			KeyboardVirtualKeyCode::_8,///10/0x09
			KeyboardVirtualKeyCode::_9,
			KeyboardVirtualKeyCode::_0,
			KeyboardVirtualKeyCode::MINUS,
			KeyboardVirtualKeyCode::EQUALS,
			KeyboardVirtualKeyCode::BACKSPACE,
			KeyboardVirtualKeyCode::TAB,
			KeyboardVirtualKeyCode::Q,
			KeyboardVirtualKeyCode::W,
			KeyboardVirtualKeyCode::E,
			KeyboardVirtualKeyCode::R,///20/0x13
			KeyboardVirtualKeyCode::T,
			KeyboardVirtualKeyCode::Y,
			KeyboardVirtualKeyCode::U,
			KeyboardVirtualKeyCode::I,
			KeyboardVirtualKeyCode::O,
			KeyboardVirtualKeyCode::P,
			KeyboardVirtualKeyCode::LBRACKET,
			KeyboardVirtualKeyCode::RBRACKET,
			KeyboardVirtualKeyCode::ENTER,
			KeyboardVirtualKeyCode::L_CTRL,///30/0x1D
			KeyboardVirtualKeyCode::A,
			KeyboardVirtualKeyCode::S,
			KeyboardVirtualKeyCode::D,
			KeyboardVirtualKeyCode::F,
			KeyboardVirtualKeyCode::G,
			KeyboardVirtualKeyCode::H,
			KeyboardVirtualKeyCode::J,
			KeyboardVirtualKeyCode::K,
			KeyboardVirtualKeyCode::L,
			KeyboardVirtualKeyCode::SEMICOLON,///40/0x27
			KeyboardVirtualKeyCode::APOSTROPHE,
			KeyboardVirtualKeyCode::GRAVE,
			KeyboardVirtualKeyCode::L_SHIFT,
			KeyboardVirtualKeyCode::BACK_SLASH,
			KeyboardVirtualKeyCode::Z,
			KeyboardVirtualKeyCode::X,
			KeyboardVirtualKeyCode::C,
			KeyboardVirtualKeyCode::V,
			KeyboardVirtualKeyCode::B,
			KeyboardVirtualKeyCode::N,///50/0x31
			KeyboardVirtualKeyCode::M,
			KeyboardVirtualKeyCode::COMMA,
			KeyboardVirtualKeyCode::PERIOD,
			KeyboardVirtualKeyCode::SLASH,
			KeyboardVirtualKeyCode::R_SHIFT,
			KeyboardVirtualKeyCode::MULTIPLY,
			KeyboardVirtualKeyCode::L_ALT,
			KeyboardVirtualKeyCode::SPACE,
			KeyboardVirtualKeyCode::CAPS_LOCK,
			KeyboardVirtualKeyCode::F1,///60/0x3B
			KeyboardVirtualKeyCode::F2,
			KeyboardVirtualKeyCode::F3,
			KeyboardVirtualKeyCode::F4,
			KeyboardVirtualKeyCode::F5,
			KeyboardVirtualKeyCode::F6,
			KeyboardVirtualKeyCode::F7,
			KeyboardVirtualKeyCode::F8,
			KeyboardVirtualKeyCode::F9,
			KeyboardVirtualKeyCode::F10,
			KeyboardVirtualKeyCode::NUM_LOCK,///70/0x45
			KeyboardVirtualKeyCode::SCORLL,
			KeyboardVirtualKeyCode::NUMPAD_7,
			KeyboardVirtualKeyCode::NUMPAD_8,
			KeyboardVirtualKeyCode::NUMPAD_9,
			KeyboardVirtualKeyCode::SUBTRACT,
			KeyboardVirtualKeyCode::NUMPAD_4,
			KeyboardVirtualKeyCode::NUMPAD_5,
			KeyboardVirtualKeyCode::NUMPAD_6,
			KeyboardVirtualKeyCode::ADD,
			KeyboardVirtualKeyCode::NUMPAD_1,///80/0x4F
			KeyboardVirtualKeyCode::NUMPAD_2,
			KeyboardVirtualKeyCode::NUMPAD_3,
			KeyboardVirtualKeyCode::NUMPAD_0,
			KeyboardVirtualKeyCode::DECIMAL,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::OEM_102,
			KeyboardVirtualKeyCode::F11,
			KeyboardVirtualKeyCode::F12,
			KeyboardVirtualKeyCode::UNKNOWN,///90/0x59
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///100/0x63
			KeyboardVirtualKeyCode::F13,
			KeyboardVirtualKeyCode::F14,
			KeyboardVirtualKeyCode::F15,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///110/0x6D
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::KANA,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_ABNT_C1
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///120/0x77
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::CONVERT,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::NOCONVERT,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_YEN
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_ABNT_C2
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///130/0x81
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///140/0x8B
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_NUMPADEQUALS
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::MEDIA_PREV_TRACK,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_AT
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_COLON
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_UNDERLINE
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_KANJI
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_STOP ///150/0x95
			KeyboardVirtualKeyCode::AX,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_UNLABELED
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::MEDIA_NEXT_TRACK,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::NUMPAD_ENTER,
			KeyboardVirtualKeyCode::R_CTRL,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///160/0x9F
			KeyboardVirtualKeyCode::VOLUME_MUTE,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_CALCULATOR
			KeyboardVirtualKeyCode::MEDIA_PLAY_PAUSE,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::MEDIA_STOP,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///170/0xA9
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::VOLUME_DOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::VOLUME_UP,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::WEB_HOME,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_NUMPADCOMMA ///180/0xB3
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::DIVIDE,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_SYSRQ
			KeyboardVirtualKeyCode::R_ALT,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///190/0xBD
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::PAUSE,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::HONE,///200/0xC7
			KeyboardVirtualKeyCode::UP,
			KeyboardVirtualKeyCode::PAGE_UP,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::LEFT,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::RIGHT,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::END,
			KeyboardVirtualKeyCode::DOWN,
			KeyboardVirtualKeyCode::PAGE_DOWN,///210/0xD1
			KeyboardVirtualKeyCode::INSERT,
			KeyboardVirtualKeyCode::DEL,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::L_WIN,///220/0xDB
			KeyboardVirtualKeyCode::R_WIN,
			KeyboardVirtualKeyCode::APPS,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_POWER
			KeyboardVirtualKeyCode::SLEEP,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,//WAKE
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::WEB_SEARCH,///230/0xE5
			KeyboardVirtualKeyCode::WEB_FAVORITES,
			KeyboardVirtualKeyCode::WEB_REFRESH,
			KeyboardVirtualKeyCode::WEB_STOP,
			KeyboardVirtualKeyCode::WEB_FORWARD,
			KeyboardVirtualKeyCode::WEB_BACK,
			KeyboardVirtualKeyCode::UNKNOWN,//DIK_MYCOMPUTER
			KeyboardVirtualKeyCode::LAUNCH_MAIL,
			KeyboardVirtualKeyCode::LAUNCH_MEDIA_SELECT,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///240/0xE9
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,///250/0xF9
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN,
			KeyboardVirtualKeyCode::UNKNOWN
		};
	};
}