#pragma once

#include "DeviceBase.h"
#include "srk/modules/inputs/GenericKeyboard.h"

namespace srk::modules::inputs::direct_input {
	class SRK_MODULE_DLL KeyboardDriver : public IGenericKeyboardDriver {
	public:
		virtual ~KeyboardDriver();

		static KeyboardDriver* SRK_CALL create(Input& input, srk_IDirectInputDevice* dev);

		virtual bool SRK_CALL readStateFromDevice(GenericKeyboard::Buffer& buffer) const override;

	private:
		KeyboardDriver(Input& input, srk_IDirectInputDevice* dev);

		IntrusivePtr<Input> _input;
		srk_IDirectInputDevice* _dev;

		inline static constexpr KeyboardVirtualKeyCode VK_MAPPER[] = {
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::ESCAPE,
			KeyboardVirtualKeyCode::_1,
			KeyboardVirtualKeyCode::_2,
			KeyboardVirtualKeyCode::_3,
			KeyboardVirtualKeyCode::_4,
			KeyboardVirtualKeyCode::_5,
			KeyboardVirtualKeyCode::_6,
			KeyboardVirtualKeyCode::_7,
			KeyboardVirtualKeyCode::_8,///10/0x09
			KeyboardVirtualKeyCode::_9,
			KeyboardVirtualKeyCode::_0,
			KeyboardVirtualKeyCode::MINUS,
			KeyboardVirtualKeyCode::EQUAL,
			KeyboardVirtualKeyCode::BACKSPACE,
			KeyboardVirtualKeyCode::TAB,
			KeyboardVirtualKeyCode::Q,
			KeyboardVirtualKeyCode::W,
			KeyboardVirtualKeyCode::E,
			KeyboardVirtualKeyCode::R,///20/0x13
			KeyboardVirtualKeyCode::T,
			KeyboardVirtualKeyCode::Y,
			KeyboardVirtualKeyCode::U,
			KeyboardVirtualKeyCode::I,
			KeyboardVirtualKeyCode::O,
			KeyboardVirtualKeyCode::P,
			KeyboardVirtualKeyCode::LEFT_BRACKET,
			KeyboardVirtualKeyCode::RIGHT_BRACKET,
			KeyboardVirtualKeyCode::ENTER,
			KeyboardVirtualKeyCode::L_CONTROL,///30/0x1D
			KeyboardVirtualKeyCode::A,
			KeyboardVirtualKeyCode::S,
			KeyboardVirtualKeyCode::D,
			KeyboardVirtualKeyCode::F,
			KeyboardVirtualKeyCode::G,
			KeyboardVirtualKeyCode::H,
			KeyboardVirtualKeyCode::J,
			KeyboardVirtualKeyCode::K,
			KeyboardVirtualKeyCode::L,
			KeyboardVirtualKeyCode::SEMICOLON,///40/0x27
			KeyboardVirtualKeyCode::APOSTROPHE,
			KeyboardVirtualKeyCode::GRAVE,
			KeyboardVirtualKeyCode::L_SHIFT,
			KeyboardVirtualKeyCode::BACK_SLASH,
			KeyboardVirtualKeyCode::Z,
			KeyboardVirtualKeyCode::X,
			KeyboardVirtualKeyCode::C,
			KeyboardVirtualKeyCode::V,
			KeyboardVirtualKeyCode::B,
			KeyboardVirtualKeyCode::N,///50/0x31
			KeyboardVirtualKeyCode::M,
			KeyboardVirtualKeyCode::COMMA,
			KeyboardVirtualKeyCode::DOT,
			KeyboardVirtualKeyCode::SLASH,
			KeyboardVirtualKeyCode::R_SHIFT,
			KeyboardVirtualKeyCode::NUMPAD_MULTIPLY,
			KeyboardVirtualKeyCode::L_ALT,
			KeyboardVirtualKeyCode::SPACE,
			KeyboardVirtualKeyCode::CAPS_LOCK,
			KeyboardVirtualKeyCode::F1,///60/0x3B
			KeyboardVirtualKeyCode::F2,
			KeyboardVirtualKeyCode::F3,
			KeyboardVirtualKeyCode::F4,
			KeyboardVirtualKeyCode::F5,
			KeyboardVirtualKeyCode::F6,
			KeyboardVirtualKeyCode::F7,
			KeyboardVirtualKeyCode::F8,
			KeyboardVirtualKeyCode::F9,
			KeyboardVirtualKeyCode::F10,
			KeyboardVirtualKeyCode::NUM_LOCK,///70/0x45
			KeyboardVirtualKeyCode::SCORLL_LOCK,
			KeyboardVirtualKeyCode::NUMPAD_7,
			KeyboardVirtualKeyCode::NUMPAD_8,
			KeyboardVirtualKeyCode::NUMPAD_9,
			KeyboardVirtualKeyCode::NUMPAD_MINUS,
			KeyboardVirtualKeyCode::NUMPAD_4,
			KeyboardVirtualKeyCode::NUMPAD_5,
			KeyboardVirtualKeyCode::NUMPAD_6,
			KeyboardVirtualKeyCode::NUMPAD_ADD,
			KeyboardVirtualKeyCode::NUMPAD_1,///80/0x4F
			KeyboardVirtualKeyCode::NUMPAD_2,
			KeyboardVirtualKeyCode::NUMPAD_3,
			KeyboardVirtualKeyCode::NUMPAD_0,
			KeyboardVirtualKeyCode::NUMPAD_DOT,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//OEM_102
			KeyboardVirtualKeyCode::F11,
			KeyboardVirtualKeyCode::F12,
			KeyboardVirtualKeyCode::UNDEFINED,///90/0x59
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///100/0x63
			KeyboardVirtualKeyCode::F13,
			KeyboardVirtualKeyCode::F14,
			KeyboardVirtualKeyCode::F15,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///110/0x6D
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//KANA
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_ABNT_C1
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///120/0x77
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//CONVERT
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//NOCONVERT
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_YEN
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_ABNT_C2
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///130/0x81
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///140/0x8B
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_NUMPADEQUALS
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//MEDIA_PREV_TRACK
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_AT
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_COLON
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_UNDERLINE
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_KANJI
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_STOP ///150/0x95
			KeyboardVirtualKeyCode::UNDEFINED,//AX
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_UNLABELED
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//MEDIA_NEXT_TRACK
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::NUMPAD_ENTER,
			KeyboardVirtualKeyCode::R_CONTROL,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///160/0x9F
			KeyboardVirtualKeyCode::UNDEFINED,//VOLUME_MUTE
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_CALCULATOR
			KeyboardVirtualKeyCode::UNDEFINED,//MEDIA_PLAY_PAUSE
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//MEDIA_STOP
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///170/0xA9
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//VOLUME_DOWN
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//VOLUME_UP
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_HOME
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_NUMPADCOMMA ///180/0xB3
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::NUMPAD_DIVIDE,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::PRINT_SCREEN,//DIK_SYSRQ
			KeyboardVirtualKeyCode::R_ALT,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///190/0xBD
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::PAUSE,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::HONE,///200/0xC7
			KeyboardVirtualKeyCode::UP,
			KeyboardVirtualKeyCode::PAGE_UP,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::LEFT,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::RIGHT,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::END,
			KeyboardVirtualKeyCode::DOWN,
			KeyboardVirtualKeyCode::PAGE_DOWN,///210/0xD1
			KeyboardVirtualKeyCode::INSERT,
			KeyboardVirtualKeyCode::DEL,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::L_WIN,///220/0xDB
			KeyboardVirtualKeyCode::R_WIN,
			KeyboardVirtualKeyCode::APPS,
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_POWER
			KeyboardVirtualKeyCode::UNDEFINED,//SLEEP
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//WAKE
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_SEARCH,///230/0xE5
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_FAVORITES
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_REFRESH
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_STOP
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_FORWARD
			KeyboardVirtualKeyCode::UNDEFINED,//WEB_BACK
			KeyboardVirtualKeyCode::UNDEFINED,//DIK_MYCOMPUTER
			KeyboardVirtualKeyCode::UNDEFINED,//LAUNCH_MAIL
			KeyboardVirtualKeyCode::UNDEFINED,//LAUNCH_MEDIA_SELECT
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///240/0xE9
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,///250/0xF9
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED,
			KeyboardVirtualKeyCode::UNDEFINED
		};
	};
}